spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/todoapp?serverTimezone=UTC&useLegacyDateTimeCode=false
    password: ola
    username: postgres

server:
  error:
    include-message: always
  port: 8090